<a href="https://colab.research.google.com/github/nguyenphamduyluan28-boop/THDeepLearning/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Noi dung numpy


In [1]:
import numpy as np

my_list=[1,9,15,39]
print('Python list: ',my_list)
my_numpy_array=np.array(my_list)
print('Numpy array: ',my_numpy_array)

a=np.array([1,9,15,39])
print(a)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
[ 1  9 15 39]


In [2]:
c=np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [3]:
d=np.array([
            [[1.,2.,3.],[4.,5.,6.]],
            [[7.,8.,9.],[10,11,12]]
           ])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [4]:
e=np.zeros((2,2))
f=np.ones((3,3))
print('Zeros matrix:\n',e)
print('Ones matrix:\n',f)

Zeros matrix:
 [[0. 0.]
 [0. 0.]]
Ones matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
e=np.array([[1,2,3],[44,5,6]])
print(e)
print(e.shape)
f=e.reshape(3,2)
print(f)
g=np.array([[[1,2,3],[4,5,6]],
          [[7,8,9],[110,11,12]]])
print(g)
print(g.shape)
h=g.reshape(3,4)
print('reshape (3,4)\n',h)
j=g.reshape(3,2,2)
print('reshape (3,2,2)\n',j)
k=g.reshape(2,3,2)
print('reshape (2,3,2)\n',k)

[[ 1  2  3]
 [44  5  6]]
(2, 3)
[[ 1  2]
 [ 3 44]
 [ 5  6]]
[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [110  11  12]]]
(2, 2, 3)
reshape (3,4)
 [[  1   2   3   4]
 [  5   6   7   8]
 [  9 110  11  12]]
reshape (3,2,2)
 [[[  1   2]
  [  3   4]]

 [[  5   6]
  [  7   8]]

 [[  9 110]
  [ 11  12]]]
reshape (2,3,2)
 [[[  1   2]
  [  3   4]
  [  5   6]]

 [[  7   8]
  [  9 110]
  [ 11  12]]]


In [6]:
e=np.array([[1,2,3],[4,5,6]])
f=e.flatten()
print(f)
g=np.array([[[1,2,3],[4,5,6]],
          [[7,8,9],[11,11,12]]])
j=g.flatten()
print(j)

[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 11 11 12]


In [7]:
f=np.array([1,2,3])
g=np.array([4,5,6])
h_stack=np.hstack((f,g))
print('Horizontal Append\n',h_stack)
v_stack=np.vstack((f,g))
print('Vertical Append\n',v_stack)
#

Horizontal Append
 [1 2 3 4 5 6]
Vertical Append
 [[1 2 3]
 [4 5 6]]


In [8]:
a=np.random.randint(100,size=(5,))
print('Random 1-D array\n',a)
b=np.random.randint(100,size=(3,4))
print('Random 2-D array\n',b)
c=np.random.randint(100,size=(3,4,3))
print('Random 3-D array\n',c)

Random 1-D array
 [32 32 65 86 84]
Random 2-D array
 [[75 43 13 47]
 [98 27 65 52]
 [84 35 28 29]]
Random 3-D array
 [[[ 9 97 41]
  [17 96 54]
  [91 75 98]
  [69 29 84]]

 [[64 56 56]
  [18 31 34]
  [61 13 11]
  [98 30 95]]

 [[61 43 74]
  [47 75  5]
  [31 15 50]
  [16 64 40]]]


In [9]:
a=np.random.normal(5,0.5,10)
print('Random 1-D array\n',a)

Random 1-D array
 [5.13239315 5.28041649 5.19717316 5.27101718 5.15275928 4.97790706
 5.37858471 4.69983272 4.8461415  4.81624047]


In [10]:
a=np.random.choice([2,4,6,8,10])
print(a)
b=np.random.choice([2,4,6,8,10],size=(3,5))
print(b)

6
[[ 2  2  2  6  4]
 [ 8  4  8  6  4]
 [ 2  2 10  8 10]]


In [11]:
a=np.matrix(np.ones((5,5)))
print('The matrix\n',a)
np.array(a)[2]=2
print('Change values of third row with array\n',a)
np.asarray(a)[2]=2
print('Change values of third row with asarray\n',a)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
a=np.arange(1,20)
print(a)
b=np.arange(1,20,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [13]:
a=np.linspace(1.,5.,num=10)

print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [14]:
a=np.array([(1,2,3),(4,5,6)])
print(a)
print('first row:',a[0])
print('Second row:',a[1])


[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
Second row: [4 5 6]


PanDas


In [15]:
import pandas as pd
a=pd.Series([1.,2.,3.])
print(a)
print('First value: ',a[0])
b=pd.Series([1.,2.,3.],index=['x','y','z'])
print(b)
print('First value: ',b['x'])
calories={"day1":420,"day2":380,"day3":390}
myvar=pd.Series(calories)
print(myvar)
myvar=pd.Series(calories,index=["day1","day2"])
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value:  1.0
x    1.0
y    2.0
z    3.0
dtype: float64
First value:  1.0
day1    420
day2    380
day3    390
dtype: int64
day1    420
day2    380
dtype: int64


In [16]:
h=np.array([[1,2],[3,4]])
df_h=pd.DataFrame(h)
print(df_h)
numpy_h=np.array(df_h)
print('Numpy array:\n',numpy_h)


   0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


In [17]:
dic={'Name':['John','Smith'],'Age':[30,40]}
df_dic=pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [18]:
import numpy as np
import pandas as pd

r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())

print('Chon cot so1\n', df['so1'])

print('Chon nhieu dong\n', df[0:3])

print('Chọn nhiều cột\n', df[['so1', 'so3']])

print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])

df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0 -2.221209 -1.085568 -0.310881 -0.214375
1 -0.771838 -1.202017 -1.162924  0.072370
2  0.882993 -1.526787  0.286915  0.674355
3 -0.187593  0.562731 -1.369623 -1.499563
4  0.397519  1.040746  0.252283 -2.053461
Chon cot so1
 0    -2.221209
1    -0.771838
2     0.882993
3    -0.187593
4     0.397519
5    -1.129725
6     1.450100
7    -0.260534
8    -0.478290
9    -0.007245
10    1.318477
11   -0.829708
12    2.003035
13   -0.995950
14    0.866762
15    1.977654
16   -1.395321
17   -0.887092
18   -0.784070
19    0.365287
Name: so1, dtype: float64
Chon nhieu dong
         so1       so2       so3       so4
0 -2.221209 -1.085568 -0.310881 -0.214375
1 -0.771838 -1.202017 -1.162924  0.072370
2  0.882993 -1.526787  0.286915  0.674355
Chọn nhiều cột
          so1       so3
0  -2.221209 -0.310881
1  -0.771838 -1.162924
2   0.882993  0.286915
3  -0.187593 -1.369623
4   0.397519  0.252283
5  -1.129725 -0.952615
6   1.450100 -1.749784
7  -0.260534  0.065015


In [19]:
import pandas as pd

df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]
                   }, index=[0, 1, 2])

df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]
                   }, index=[3, 4])

df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

print('Drop duplicatevalues in DataFrame\n', df_concat.drop_duplicates('Name'))

print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

df_rename = df_concat.rename(columns={'Name':'Surname', 'Age':'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


LAB2


In [20]:
import tensorflow as tf
import numpy as np

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [21]:
r1 = tf.constant(9, tf.int16)
r1_float = tf.constant(1.12, tf.float32)
r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1)
print(r1_float)
print(r1_string)

tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


In [22]:

rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [23]:

rank_2_tensor = tf.constant([[1, 2],
                              [3, 4],
                              [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [24]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [25]:
t_zero = tf.zeros(10)
print(t_zero)

t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


In [26]:
t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3, 3])
print(t_2_one)

t_3_one = tf.ones([3, 3, 5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


In [27]:
t_1 = tf.fill(3, 10)
print(t_1)

t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


In [28]:
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


In [29]:
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

range_tensor = tf.range(3.0, delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


In [30]:
range_tensor = tf.random.normal([5])
print(range_tensor)

range_tensor = tf.random.normal([3, 3])
print(range_tensor)

range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

range_tensor = tf.random.truncated_normal([3, 2])
print(range_tensor)

range_tensor = tf.random.truncated_normal([3, 2, 2])
print(range_tensor)

range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)

range_tensor = tf.random.uniform([3, 2], minval=10, maxval=20)
print(range_tensor)

range_tensor = tf.random.uniform([3, 2, 5], minval=10, maxval=20)
print(range_tensor)

range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)
print(tf.random.shuffle(range_tensor))

tf.Tensor([ 1.5753157   0.07725661  1.1952605  -0.19704466 -2.8119018 ], shape=(5,), dtype=float32)
tf.Tensor(
[[-0.5745706  -0.519244    1.2313702 ]
 [ 0.05655631  0.26662448 -0.24464539]
 [-1.6838048   1.4412442   0.6668782 ]], shape=(3, 3), dtype=float32)
tf.Tensor([-1.2318206  -0.52485865 -0.7824221  -0.01656346  1.073567  ], shape=(5,), dtype=float32)
tf.Tensor(
[[ 0.92149717  0.52879065]
 [ 0.4631915  -1.1816782 ]
 [ 1.1077156   0.8799576 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[-1.1449846  -0.60320306]
  [ 1.3335096  -0.24295028]]

 [[ 1.2961577   0.71114504]
  [ 1.0894754   0.7462562 ]]

 [[ 1.0654004   0.32893267]
  [ 0.61196995  1.5373722 ]]], shape=(3, 2, 2), dtype=float32)
tf.Tensor([11.596617  17.378918  11.378122  14.682306  10.6639185], shape=(5,), dtype=float32)
tf.Tensor(
[[18.887344 16.72938 ]
 [19.068947 13.333851]
 [12.087351 10.745148]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[17.855133 14.712894 13.575591 16.71297  10.680585]
  [13.017252 17.090866 10.559

In [31]:
t_float = tf.constant(3.9, tf.float32)
print(t_float, '----', t_float.dtype)
t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int, '----', t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) ---- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) ---- <dtype: 'int32'>


In [32]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])
r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)
print(r4)

tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


In [33]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3],
                   [4, 5, 6]])
t4 = tf.constant([[7, 8],
                   [9, 10],
                   [11, 12]])
dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)
print(t1)
print(t2)
print(t3)
print(t4)
cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)
print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)
tf.Tensor([3. 2. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [34]:
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
print('Shape', diem.shape)
print('Dtype', diem.dtype)
print('numpy:', diem.numpy())

toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
diem.assign([8, 10])
print(diem)

toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
diem.assign([8, 10])
diem.assign_add([1, 1])
print(diem)
diem.assign_sub([5, 5])
print(diem)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
Shape (2,)
Dtype <dtype: 'int32'>
numpy: [5 9]
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 11], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 6], dtype=int32)>


In [35]:
def a_regular_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

a_function_that_uses_a_graph = tf.function(a_regular_function)

x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()
print(orig_value)
print(tf_function_value)

def inner_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

@tf.function
def outer_function(x):
    y = tf.constant([[2.0], [3.0]])
    b = tf.constant(4.0)
    return inner_function(x, y, b)

rs = outer_function(tf.constant([[1.0, 2.0]])).numpy()
print(rs)

[[12.]]
[[12.]]
[[12.]]


In [36]:
class SimpleModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.a_variable = tf.Variable(5.0, name="train_me")
        self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")
    def __call__(self, x):
        return self.a_variable * x + self.non_trainable_variable

simple_module = SimpleModule(name="simple")
rs = simple_module(tf.constant(5.0))
print(rs)
print('Train variables', simple_module.trainable_variables)
print('All variables', simple_module.variables)

class Dense(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        self.w = tf.Variable(
            tf.random.normal([in_features, out_features]), name='w')
        self.b = tf.Variable(tf.zeros([out_features]), name='b')
    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)

class SequentialModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.dense_1 = Dense(in_features=3, out_features=3)
        self.dense_2 = Dense(in_features=3, out_features=2)
    def __call__(self, x):
        x = self.dense_1(x)
        return self.dense_2(x)

my_model = SequentialModule(name="the_model")
print("Model results:", my_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor(30.0, shape=(), dtype=float32)
Train variables (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
All variables (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'do_not_train_me:0' shape=() dtype=float32, numpy=5.0>)
Model results: tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)


In [37]:
chkp_path = "my_checkpoint"
checkpoint = tf.train.Checkpoint(model=my_model)
checkpoint.write(chkp_path)

new_model = SequentialModule()
new_checkpoint = tf.train.Checkpoint(model=new_model)
new_checkpoint.restore("my_checkpoint")
print(new_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
