<a href="https://colab.research.google.com/github/nguyenphamduyluan28-boop/THDeepLearning/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Noi dung numpy


In [2]:
import numpy as np

my_list=[1,9,15,39]
print('Python list: ',my_list)
my_numpy_array=np.array(my_list)
print('Numpy array: ',my_numpy_array)

a=np.array([1,9,15,39])
print(a)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
[ 1  9 15 39]


In [5]:
c=np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [8]:
d=np.array([
            [[1.,2.,3.],[4.,5.,6.]],
            [[7.,8.,9.],[10,11,12]]
           ])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [11]:
e=np.zeros((2,2))
f=np.ones((3,3))
print('Zeros matrix:\n',e)
print('Ones matrix:\n',f)

Zeros matrix:
 [[0. 0.]
 [0. 0.]]
Ones matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
e=np.array([[1,2,3],[44,5,6]])
print(e)
print(e.shape)
f=e.reshape(3,2)
print(f)
g=np.array([[[1,2,3],[4,5,6]],
          [[7,8,9],[110,11,12]]])
print(g)
print(g.shape)
h=g.reshape(3,4)
print('reshape (3,4)\n',h)
j=g.reshape(3,2,2)
print('reshape (3,2,2)\n',j)
k=g.reshape(2,3,2)
print('reshape (2,3,2)\n',k)

[[ 1  2  3]
 [44  5  6]]
(2, 3)
[[ 1  2]
 [ 3 44]
 [ 5  6]]
[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [110  11  12]]]
(2, 2, 3)
reshape (3,4)
 [[  1   2   3   4]
 [  5   6   7   8]
 [  9 110  11  12]]
reshape (3,2,2)
 [[[  1   2]
  [  3   4]]

 [[  5   6]
  [  7   8]]

 [[  9 110]
  [ 11  12]]]
reshape (2,3,2)
 [[[  1   2]
  [  3   4]
  [  5   6]]

 [[  7   8]
  [  9 110]
  [ 11  12]]]


In [16]:
e=np.array([[1,2,3],[4,5,6]])
f=e.flatten()
print(f)
g=np.array([[[1,2,3],[4,5,6]],
          [[7,8,9],[11,11,12]]])
j=g.flatten()
print(j)

[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 11 11 12]


In [17]:
f=np.array([1,2,3])
g=np.array([4,5,6])
h_stack=np.hstack((f,g))
print('Horizontal Append\n',h_stack)
v_stack=np.vstack((f,g))
print('Vertical Append\n',v_stack)
#

Horizontal Append
 [1 2 3 4 5 6]
Vertical Append
 [[1 2 3]
 [4 5 6]]


In [18]:
a=np.random.randint(100,size=(5,))
print('Random 1-D array\n',a)
b=np.random.randint(100,size=(3,4))
print('Random 2-D array\n',b)
c=np.random.randint(100,size=(3,4,3))
print('Random 3-D array\n',c)

Random 1-D array
 [ 9 75 46 37  8]
Random 2-D array
 [[79 37 98  2]
 [85 46 40 29]
 [84 89 27 63]]
Random 3-D array
 [[[31 46 47]
  [30  8 94]
  [63 21 36]
  [ 8 46 28]]

 [[ 2 87 69]
  [64 31 60]
  [82  7 30]
  [30  9 85]]

 [[85 23 39]
  [54 66 78]
  [84 10 19]
  [ 9 28 53]]]


In [21]:
a=np.random.normal(5,0.5,10)
print('Random 1-D array\n',a)

Random 1-D array
 [4.66966417 5.55165267 4.80370603 4.4803636  5.0669974  4.87795856
 6.05030673 4.78795377 5.21723366 5.00240534]


In [23]:
a=np.random.choice([2,4,6,8,10])
print(a)
b=np.random.choice([2,4,6,8,10],size=(3,5))
print(b)

4
[[ 6  2 10  4  8]
 [ 8  4  4  4 10]
 [ 6  8  8  8  6]]


In [24]:
a=np.matrix(np.ones((5,5)))
print('The matrix\n',a)
np.array(a)[2]=2
print('Change values of third row with array\n',a)
np.asarray(a)[2]=2
print('Change values of third row with asarray\n',a)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
a=np.arange(1,20)
print(a)
b=np.arange(1,20,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [26]:
a=np.linspace(1.,5.,num=10)

print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [28]:
a=np.array([(1,2,3),(4,5,6)])
print(a)
print('first row:',a[0])
print('Second row:',a[1])


[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
Second row: [4 5 6]


PanDas


In [29]:
import pandas as pd
a=pd.Series([1.,2.,3.])
print(a)
print('First value: ',a[0])
b=pd.Series([1.,2.,3.],index=['x','y','z'])
print(b)
print('First value: ',b['x'])
calories={"day1":420,"day2":380,"day3":390}
myvar=pd.Series(calories)
print(myvar)
myvar=pd.Series(calories,index=["day1","day2"])
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value:  1.0
x    1.0
y    2.0
z    3.0
dtype: float64
First value:  1.0
day1    420
day2    380
day3    390
dtype: int64
day1    420
day2    380
dtype: int64


In [30]:
h=np.array([[1,2],[3,4]])
df_h=pd.DataFrame(h)
print(df_h)
numpy_h=np.array(df_h)
print('Numpy array:\n',numpy_h)


   0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


In [31]:
dic={'Name':['John','Smith'],'Age':[30,40]}
df_dic=pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [32]:
import numpy as np
import pandas as pd

r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())

print('Chon cot so1\n', df['so1'])

print('Chon nhieu dong\n', df[0:3])

print('Chọn nhiều cột\n', df[['so1', 'so3']])

print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])

df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0  0.134348 -0.465645 -0.653961  0.417220
1  0.625315  1.359481  1.776745  1.099617
2 -0.683989  1.347709  0.888454 -1.536949
3  0.373652  1.002701 -0.175110  0.351628
4  0.886917 -0.873544 -2.414693  1.275556
Chon cot so1
 0     0.134348
1     0.625315
2    -0.683989
3     0.373652
4     0.886917
5    -1.673122
6     0.645344
7     1.104417
8    -0.867179
9     1.984077
10    0.754585
11    0.882161
12   -0.536494
13    0.699456
14    0.572678
15   -1.572788
16    0.612857
17    0.351506
18    0.655915
19   -0.083012
Name: so1, dtype: float64
Chon nhieu dong
         so1       so2       so3       so4
0  0.134348 -0.465645 -0.653961  0.417220
1  0.625315  1.359481  1.776745  1.099617
2 -0.683989  1.347709  0.888454 -1.536949
Chọn nhiều cột
          so1       so3
0   0.134348 -0.653961
1   0.625315  1.776745
2  -0.683989  0.888454
3   0.373652 -0.175110
4   0.886917 -2.414693
5  -1.673122  1.649967
6   0.645344  1.672482
7   1.104417  1.159575


In [33]:
import pandas as pd

df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]
                   }, index=[0, 1, 2])

df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]
                   }, index=[3, 4])

df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

print('Drop duplicatevalues in DataFrame\n', df_concat.drop_duplicates('Name'))

print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

df_rename = df_concat.rename(columns={'Name':'Surname', 'Age':'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


LAB2


In [34]:
import tensorflow as tf
import numpy as np

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [35]:
r1 = tf.constant(9, tf.int16)
r1_float = tf.constant(1.12, tf.float32)
r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1)
print(r1_float)
print(r1_string)

tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


In [ ]:

rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

In [ ]:

rank_2_tensor = tf.constant([[1, 2],
                              [3, 4],
                              [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

In [ ]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],])
print(rank_3_tensor)

In [36]:
t_zero = tf.zeros(10)
print(t_zero)

t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


In [ ]:
t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3, 3])
print(t_2_one)

t_3_one = tf.ones([3, 3, 5])
print(t_3_one)

In [ ]:
t_1 = tf.fill(3, 10)
print(t_1)

t_2 = tf.fill([3, 3], 9)
print(t_2)

In [ ]:
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

In [ ]:
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

range_tensor = tf.range(3.0, delta=0.5)
print(range_tensor)

In [37]:
range_tensor = tf.random.normal([5])
print(range_tensor)

range_tensor = tf.random.normal([3, 3])
print(range_tensor)

range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

range_tensor = tf.random.truncated_normal([3, 2])
print(range_tensor)

range_tensor = tf.random.truncated_normal([3, 2, 2])
print(range_tensor)

range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)

range_tensor = tf.random.uniform([3, 2], minval=10, maxval=20)
print(range_tensor)

range_tensor = tf.random.uniform([3, 2, 5], minval=10, maxval=20)
print(range_tensor)

range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)
print(tf.random.shuffle(range_tensor))

tf.Tensor([ 2.3983915  -0.73566365  1.1793557   0.28143486  0.43715593], shape=(5,), dtype=float32)
tf.Tensor(
[[-0.5247941  -1.4000173  -1.5859965 ]
 [ 0.3208004   0.04185066  0.76985884]
 [-0.98780304 -1.2458464  -1.4383944 ]], shape=(3, 3), dtype=float32)
tf.Tensor([-1.2167815   0.6845143   0.7217697  -0.6115686  -0.09145392], shape=(5,), dtype=float32)
tf.Tensor(
[[ 0.5883465 -1.2564149]
 [ 1.0885386  1.3536344]
 [ 1.7474647  0.9125068]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[ 0.6882569   0.23686187]
  [ 0.61243814  0.67797637]]

 [[-1.8364323   0.8707103 ]
  [ 0.487047   -0.49869758]]

 [[-1.6106039  -1.080895  ]
  [-0.93135786 -0.7042006 ]]], shape=(3, 2, 2), dtype=float32)
tf.Tensor([19.453325 13.472873 13.35641  19.581072 13.334637], shape=(5,), dtype=float32)
tf.Tensor(
[[17.299547 12.53801 ]
 [11.534939 14.228963]
 [14.640324 18.992764]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[13.604967  11.292615  10.36996   18.636728  16.209812 ]
  [17.276201  14.7275505 10.004932 

In [38]:
t_float = tf.constant(3.9, tf.float32)
print(t_float, '----', t_float.dtype)
t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int, '----', t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) ---- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) ---- <dtype: 'int32'>


In [ ]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])
r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)
print(r4)

In [ ]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3],
                   [4, 5, 6]])
t4 = tf.constant([[7, 8],
                   [9, 10],
                   [11, 12]])
dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)
print(t1)
print(t2)
print(t3)
print(t4)
cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)
print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

In [ ]:
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
print('Shape', diem.shape)
print('Dtype', diem.dtype)
print('numpy:', diem.numpy())

toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
diem.assign([8, 10])
print(diem)

toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
diem.assign([8, 10])
diem.assign_add([1, 1])
print(diem)
diem.assign_sub([5, 5])
print(diem)

In [ ]:
def a_regular_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

a_function_that_uses_a_graph = tf.function(a_regular_function)

x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()
print(orig_value)
print(tf_function_value)

def inner_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

@tf.function
def outer_function(x):
    y = tf.constant([[2.0], [3.0]])
    b = tf.constant(4.0)
    return inner_function(x, y, b)

rs = outer_function(tf.constant([[1.0, 2.0]])).numpy()
print(rs)

In [39]:
class SimpleModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.a_variable = tf.Variable(5.0, name="train_me")
        self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")
    def __call__(self, x):
        return self.a_variable * x + self.non_trainable_variable

simple_module = SimpleModule(name="simple")
rs = simple_module(tf.constant(5.0))
print(rs)
print('Train variables', simple_module.trainable_variables)
print('All variables', simple_module.variables)

class Dense(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        self.w = tf.Variable(
            tf.random.normal([in_features, out_features]), name='w')
        self.b = tf.Variable(tf.zeros([out_features]), name='b')
    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)

class SequentialModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.dense_1 = Dense(in_features=3, out_features=3)
        self.dense_2 = Dense(in_features=3, out_features=2)
    def __call__(self, x):
        x = self.dense_1(x)
        return self.dense_2(x)

my_model = SequentialModule(name="the_model")
print("Model results:", my_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor(30.0, shape=(), dtype=float32)
Train variables (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
All variables (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'do_not_train_me:0' shape=() dtype=float32, numpy=5.0>)
Model results: tf.Tensor([[4.2621684 1.4340694]], shape=(1, 2), dtype=float32)


In [40]:
chkp_path = "my_checkpoint"
checkpoint = tf.train.Checkpoint(model=my_model)
checkpoint.write(chkp_path)

new_model = SequentialModule()
new_checkpoint = tf.train.Checkpoint(model=new_model)
new_checkpoint.restore("my_checkpoint")
print(new_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor([[4.2621684 1.4340694]], shape=(1, 2), dtype=float32)
