<a href="https://colab.research.google.com/github/nguyenphamduyluan28-boop/THDeepLearning/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

my_list=[1,9,15,39]
print('Python list: ',my_list)
my_numpy_array=np.array(my_list)
print('Numpy array: ',my_numpy_array)

a=np.array([1,9,15,39])
print(a)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
[ 1  9 15 39]


In [5]:
c=np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [8]:
d=np.array([
            [[1.,2.,3.],[4.,5.,6.]],
            [[7.,8.,9.],[10,11,12]]
           ])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [11]:
e=np.zeros((2,2))
f=np.ones((3,3))
print('Zeros matrix:\n',e)
print('Ones matrix:\n',f)

Zeros matrix:
 [[0. 0.]
 [0. 0.]]
Ones matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
e=np.array([[1,2,3],[44,5,6]])
print(e)
print(e.shape)
f=e.reshape(3,2)
print(f)
g=np.array([[[1,2,3],[4,5,6]],
          [[7,8,9],[110,11,12]]])
print(g)
print(g.shape)
h=g.reshape(3,4)
print('reshape (3,4)\n',h)
j=g.reshape(3,2,2)
print('reshape (3,2,2)\n',j)
k=g.reshape(2,3,2)
print('reshape (2,3,2)\n',k)

[[ 1  2  3]
 [44  5  6]]
(2, 3)
[[ 1  2]
 [ 3 44]
 [ 5  6]]
[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [110  11  12]]]
(2, 2, 3)
reshape (3,4)
 [[  1   2   3   4]
 [  5   6   7   8]
 [  9 110  11  12]]
reshape (3,2,2)
 [[[  1   2]
  [  3   4]]

 [[  5   6]
  [  7   8]]

 [[  9 110]
  [ 11  12]]]
reshape (2,3,2)
 [[[  1   2]
  [  3   4]
  [  5   6]]

 [[  7   8]
  [  9 110]
  [ 11  12]]]


In [16]:
e=np.array([[1,2,3],[4,5,6]])
f=e.flatten()
print(f)
g=np.array([[[1,2,3],[4,5,6]],
          [[7,8,9],[11,11,12]]])
j=g.flatten()
print(j)

[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 11 11 12]


In [17]:
f=np.array([1,2,3])
g=np.array([4,5,6])
h_stack=np.hstack((f,g))
print('Horizontal Append\n',h_stack)
v_stack=np.vstack((f,g))
print('Vertical Append\n',v_stack)
#

Horizontal Append
 [1 2 3 4 5 6]
Vertical Append
 [[1 2 3]
 [4 5 6]]


In [18]:
a=np.random.randint(100,size=(5,))
print('Random 1-D array\n',a)
b=np.random.randint(100,size=(3,4))
print('Random 2-D array\n',b)
c=np.random.randint(100,size=(3,4,3))
print('Random 3-D array\n',c)

Random 1-D array
 [ 9 75 46 37  8]
Random 2-D array
 [[79 37 98  2]
 [85 46 40 29]
 [84 89 27 63]]
Random 3-D array
 [[[31 46 47]
  [30  8 94]
  [63 21 36]
  [ 8 46 28]]

 [[ 2 87 69]
  [64 31 60]
  [82  7 30]
  [30  9 85]]

 [[85 23 39]
  [54 66 78]
  [84 10 19]
  [ 9 28 53]]]


In [21]:
a=np.random.normal(5,0.5,10)
print('Random 1-D array\n',a)

Random 1-D array
 [4.66966417 5.55165267 4.80370603 4.4803636  5.0669974  4.87795856
 6.05030673 4.78795377 5.21723366 5.00240534]


In [23]:
a=np.random.choice([2,4,6,8,10])
print(a)
b=np.random.choice([2,4,6,8,10],size=(3,5))
print(b)

4
[[ 6  2 10  4  8]
 [ 8  4  4  4 10]
 [ 6  8  8  8  6]]
